### ISSUE TITLE
protocol web server hang up error

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_protocols_web#24]
The following error occurred.
```
Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketOnEnd [as onend] (http.js:1568:23)
    at Socket.g (events.js:180:16)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by eskim** [comment]
음.. 조금더 상황을 구체적으로 설명해 주실수 있나요?
구동시에 발생하나요? 아니면 동작중에 발생하나요?

**Comment by dwlee** [comment]
rocon_protocols_webserver가 동작하지 않아 다음과 확인하니 위의 로그를 출력하고 죽었습니다.

**Comment by eskim** [comment]
네트워크 관련된 에러 같네요 
서버 시작에는 문제가 없죠?

**Comment by dwlee** [comment]
네 문제는 없습니다. 발생한 로그를 캡쳐하여 메일로 전달해 드렸습니다.

**Comment by eskim** [comment]
다시 발생하지 않는 것으로 보입니다.
