### ISSUE TITLE
Message synch error

### ISSUE THREAD

**Issue by hughie** [robotics-in-concert/rocon_protocols_web#35]
hic app 업데이트 중에 com.github.turtlebot.turtlebot_android.voice_commander.indigo 
err:  [TypeError: Cannot read property 'length' of null]
와 같은 에러가 나는데, 어디를 보아야 할까요?

---

rocondev@wagner:~/rocon/web_ws/src/rocon_protocols_web/rocon_protocols_webserver$ node scheduler.js --start-sync-message
[Error: /home/rocondev/rocon/web_ws/src/rocon_protocols_web/rocon_protocols_webserver/node_modules/mongodb/node_modules/bson/build/Release/bson.node: undefined symbol: node_module_register]
js-bson: Failed to load c++ bson extension, using pure JS version
mongo connected
start to sync message
[msg.js] sync start
scheduler started
updated hic app :  rocon_gateway_graph
updated hic app :  web_url(http://www.google.com)
updated hic app :  concert_teleop
updated hic app :  rocon_qt_listener/qt_listener.py
updated hic app :  com.github.rosjava.android_remocons.listener.Listener
updated hic app :  com.UnityPlayerNativeActivity
updated hic app :  concert_conductor_graph
updated hic app :  web_url(http://www.google.com)
updated hic app :  concert_make_a_map
updated hic app :  com.github.rosjava.android_apps.map_nav.MainActivity
updated hic app :  com.github.rosjava.android_apps.teleop.MainActivity
updated hic app :  rqt_graph
updated hic app :  web_app(http://**WEBSERVER_ADDRESS**/concert_common_web_interface/pickup_delivery_order/index.html)
updated hic app :  concert_map_annotation
updated hic app :  com.github.rosjava.android_apps.make_a_map.MainActivity
updated hic app :  web_url(http://www.google.com)
updated hic app :  concert_info
updated hic app :  web_url(http://www.google.com)
updated hic app :  turtlebot_teleop/keyboard_teleop.launch
updated hic app :  com.github.turtlebot.turtlebot_android.panorama.PanoramaActivity
updated hic app :  com.github.robotics_in_concert.rocon_android_apps.beacon_awareness_ex.BeaconAwarenessExMainActivity
updated hic app :  concert_admin_app
updated hic app :  web_app(http://**WEBSERVER_ADDRESS**/vm_delivery_order/index.html)
updated hic app :  rocon_teleop
updated hic app :  com.github.turtlebot.turtlebot_android.follower.FollowerActivity
updated hic app :  com.github.turtlebot.turtlebot_android.voice_commander.indigo
err:  [TypeError: Cannot read property 'length' of null]
simple_delivery_robot_ctrl synced
rocon_smartthings_rapps synced
rocon_hue synced
rapix_bridge synced
rapix_bridge synced
vm_delivery_robot_ctrl synced
robosem_bridge synced
rocon_auto_door synced
robosem_bridge synced
robosem_bridge synced
concert_demo_rapps synced
rocon_auto_door synced
rocon_hue synced
rocon_apps synced
concert_demo_sim_rapps synced
rocon_hue synced
rocon_apps synced
rocon_nao synced
rocon_ninjablock_rapps synced
rocon_ninja_block synced
irobi_bridge synced
irobi_bridge synced
failed to sync message { [Error: Command failed: Traceback (most recent call last):
  File "/opt/ros/indigo/bin/rosmsg", line 35, in <module>
    rosmsg.rosmsgmain()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmsg/**init**.py", line 747, in rosmsgmain
    rosmsg_cmd_list(ext, full)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmsg/**init**.py", line 691, in rosmsg_cmd_list
    packs = sorted([x for x in iterate_packages(rospack, mode)])
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmsg/**init**.py", line 540, in iterate_packages
    package_paths = _get_package_paths(p, rospack)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmsg/__init__.py", line 553, in _get_package_paths
    results = find_in_workspaces(search_dirs=['share'], project=pkgname, first_match_only=True, workspace_to_source_spaces=_catkin_workspace_to_source_spaces, source_path_to_packages=_catkin_source_path_to_packages)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/catkin/find_in_workspaces.py", line 142, in find_in_workspaces
    source_path_to_packages[source_path] = find_packages(source_path)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 84, in find_packages
    packages = find_packages_allowing_duplicates(basepath, exclude_paths=exclude_paths, exclude_subspaces=exclude_subspaces, warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 111, in find_packages_allowing_duplicates
    packages[path] = parse_package(os.path.join(basepath, path), warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 370, in parse_package
    return parse_package_string(f.read(), filename, warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 543, in parse_package_string
    pkg.validate(warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 244, in validate
    raise InvalidPackage('\n'.join(errors))
catkin_pkg.package.InvalidPackage: Invalid package manifest "/home/rocondev/rocon/web_ws/src/rocon_solution_webmanager/test_soluton_create/package.xml": Package name must not be empty
Package name "" does not follow naming conventions
Package version must not be empty
Package description must not be empty
Invalid email "" for person ""
Maintainers must have an email address
The package must not "exec_depend" on a package with the same name as this package
The package must not "build_export_depend" on a package with the same name as this package
]
  cause:
   { [Error: Command failed: Traceback (most recent call last):
     File "/opt/ros/indigo/bin/rosmsg", line 35, in <module>
       rosmsg.rosmsgmain()
     File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmsg/__init__.py", line 747, in rosmsgmain
       rosmsg_cmd_list(ext, full)
     File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmsg/**init**.py", line 691, in rosmsg_cmd_list
       packs = sorted([x for x in iterate_packages(rospack, mode)])
     File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmsg/**init**.py", line 540, in iterate_packages
       package_paths = _get_package_paths(p, rospack)
     File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmsg/__init__.py", line 553, in _get_package_paths
       results = find_in_workspaces(search_dirs=['share'], project=pkgname, first_match_only=True, workspace_to_source_spaces=_catkin_workspace_to_source_spaces, source_path_to_packages=_catkin_source_path_to_packages)
     File "/opt/ros/indigo/lib/python2.7/dist-packages/catkin/find_in_workspaces.py", line 142, in find_in_workspaces
       source_path_to_packages[source_path] = find_packages(source_path)
     File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 84, in find_packages
       packages = find_packages_allowing_duplicates(basepath, exclude_paths=exclude_paths, exclude_subspaces=exclude_subspaces, warnings=warnings)
     File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 111, in find_packages_allowing_duplicates
       packages[path] = parse_package(os.path.join(basepath, path), warnings=warnings)
     File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 370, in parse_package
       return parse_package_string(f.read(), filename, warnings=warnings)
     File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 543, in parse_package_string
       pkg.validate(warnings=warnings)
     File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 244, in validate
       raise InvalidPackage('\n'.join(errors))
   catkin_pkg.package.InvalidPackage: Invalid package manifest "/home/rocondev/rocon/web_ws/src/rocon_solution_webmanager/test_soluton_create/package.xml": Package name must not be empty
   Package name "" does not follow naming conventions
   Package version must not be empty
   Package description must not be empty
   Invalid email "" for person ""
   Maintainers must have an email address
   The package must not "exec_depend" on a package with the same name as this package
   The package must not "build_export_depend" on a package with the same name as this package
   ] killed: false, code: 1, signal: null },
  isOperational: true,
  killed: false,
  code: 1,
  signal: null }

**Comment by hughie** [comment]
"hic_apps_url": "https://raw.githubusercontent.com/robotics-in-concert/rocon_protocols_web/master/rocon_protocols_webserver/distro/hic_apps/hic_apps.yaml"
에는 해당하는 hic_app이 없음.

**Comment by hughie** [comment]
https://raw.githubusercontent.com/robotics-in-concert/rocon_protocols_web/master/rocon_protocols_webserver/distro/hic_apps/turtlebot_pairing.hic_apps
에는 voice commander가 없는데, synch할 때 찾음.

**Comment by hughie** [comment]
rosmsg list 명령에서 에러가 남

---

rocondev@wagner:~/rocon/web_ws/src/rocon_protocols_web/rocon_protocols_web_fetch/lib$ rosmsg list
Traceback (most recent call last):
  File "/opt/ros/indigo/bin/rosmsg", line 35, in <module>
    rosmsg.rosmsgmain()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmsg/**init**.py", line 747, in rosmsgmain
    rosmsg_cmd_list(ext, full)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmsg/**init**.py", line 691, in rosmsg_cmd_list
    packs = sorted([x for x in iterate_packages(rospack, mode)])
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmsg/**init**.py", line 540, in iterate_packages
    package_paths = _get_package_paths(p, rospack)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmsg/__init__.py", line 553, in _get_package_paths
    results = find_in_workspaces(search_dirs=['share'], project=pkgname, first_match_only=True, workspace_to_source_spaces=_catkin_workspace_to_source_spaces, source_path_to_packages=_catkin_source_path_to_packages)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/catkin/find_in_workspaces.py", line 142, in find_in_workspaces
    source_path_to_packages[source_path] = find_packages(source_path)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 84, in find_packages
    packages = find_packages_allowing_duplicates(basepath, exclude_paths=exclude_paths, exclude_subspaces=exclude_subspaces, warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 111, in find_packages_allowing_duplicates
    packages[path] = parse_package(os.path.join(basepath, path), warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 370, in parse_package
    return parse_package_string(f.read(), filename, warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 543, in parse_package_string
    pkg.validate(warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 244, in validate
    raise InvalidPackage('\n'.join(errors))
catkin_pkg.package.InvalidPackage: Invalid package manifest "/home/rocondev/rocon/web_ws/src/rocon_solution_webmanager/test_soluton_create/package.xml": Package name must not be empty
Package name "" does not follow naming conventions
Package version must not be empty
Package description must not be empty
Invalid email "" for person ""
Maintainers must have an email address
The package must not "exec_depend" on a package with the same name as this package
The package must not "build_export_depend" on a package with the same name as this package

**Comment by hughie** [comment]
solution web manager를 통해 생성된 package들이 잘못되어서 msg synch가 되지 않아서 발생한 에러!
